title: My personal webpage
description: My blog, noes, resume
google_analytics: G-9CZJL4NZPE
author: "Shahram Nikbakhtian"
theme: jekyll-theme-hacker
#github: [metadata]

github_username: "<github_username>"
facebook_username: "<facebook_username>"
twitter_username: "<twitter_username>"
linkedin_id: "<linkedin_id>"

blog: on                 # Show blog tag and post list (on | off)
theme_base: "dark"       # Theme palette (light | dark)
theme_switch: on         # Show color switch (on | off)
highlighter_theme: colorful  # Theme of the syntax_highlighter [base16 |
                            # colorful | github | gruvbox | molokai |
                            # monokai | pastie | thankful_eyes | tulip ]
toolbar_priority:        # Order of the items in the toolbar (except for blog and home)
  - About
  - Projects

recent_posts: 10

# Collections
collections:
  dropdown:
    output: true
  items:
    output: true
# ------------------------------------------------------------------------------
theme_skin: blue

sass:
  sass_dir: _sass
  style: compressed


  markdown: kramdown
